# Site settings
title: Probably a Blog
email: jpetkau@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about coding and stuff
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://jpetkau.github.io" # the base hostname & protocol for your site
twitter_username: codeproof
github_username:  jpetkau

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

theme: jekyll-theme-architect
